### ISSUE TITLE
segment-unchaptered: Field required [type=missing, input_value={'Result': {'paragraph_indexes': [0]}}, input_type=dict]

### ISSUE THREAD

**Issue by BastLeblanc** [shun-liang/yt2doc#53]
Hello !

I'm getting this error:
```
InstructorRetryException: 1 validation error for Result
paragraph_indexes
  Field required [type=missing, input_value={'Result': {'paragraph_indexes': [0]}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

in this file
```
yt2doc/.venv/lib/python3.12/site-packages/instructor/retry.py:164 in retry_sync
```

When using the `--segment-unchaptered` parameter.
Tried a few llm models, mistral:latest, llama3:latest

It seems to depends on video, some work
For example, I get this error on this one https://www.youtube.com/watch?v=-J88th7vZ34

**Comment by shun-liang** [comment]
Thanks for reporting this issue. Can you provide the version of yt2doc that you are running? You can get it with

```
pipx list
```

or 

```
uv tool list
```

Also, can you provide the full command line of how you ran it?

**Comment by BastLeblanc** [comment]
I'm not using pipx (because of this #46 bug on macos) but a python virtualenv

Version of yt2doc:
```
$ pip list|grep yt2doc 
yt2doc             0.2.8
```

The end of the log (before it's just the transcribed text):
```
Artin Chat has has been deploying it really good feedback so far so issues you know feature requests check out that GitHub repo submit those there ", 'Janon Lofty Vincent ', "great great presentation as you can see a lot of really great feedback here looking forward to seeing at this project these constructs just continue to grow and and iterate and do some really great things so we will we'll wrap it there again ", 'if anyone has any questions please feel free to reach out you can check out the cdk channel cdklive ', "just cdk.live is the website feel free to subscribe we'll always have you know content coming up every few weeks here and we also have you know previous shows previous tutorials things you can check out as well so we'll we'll call it there ", 'thank you guys for for showing up ', 'thank you for everybody here that was asking questions chatting this was it was a really great experience so we look forward to seeing you next time so thanks guys ', 'thank you ', 'thank you ', 'thank you']])]
Finding topic change points:   0%|                                                                                                                                                            | 0/8 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[1, 3]
Finding topic change points:  12%|██████████████████▌                                                                                                                                 | 1/8 [00:16<01:54, 16.42s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[3]
Finding topic change points:  25%|█████████████████████████████████████                                                                                                               | 2/8 [00:19<00:51,  8.61s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[3, 4, 5]
Finding topic change points:  38%|███████████████████████████████████████████████████████▌                                                                                            | 3/8 [00:23<00:32,  6.49s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[1, 3]
Finding topic change points:  50%|██████████████████████████████████████████████████████████████████████████                                                                          | 4/8 [00:27<00:22,  5.56s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[3, 5]
Finding topic change points:  62%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 5/8 [00:32<00:16,  5.37s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[2, 4]
Finding topic change points:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 6/8 [00:36<00:09,  4.97s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py:paragraph indexes from LLM: paragraph_indexes=[1, 3]
Finding topic change points:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7/8 [00:40<00:04,  4.53s/it]INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:11434/v1/chat/completions "HTTP/1.1 200 OK"
Finding topic change points:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 7/8 [01:07<00:09,  9.59s/it]
Traceback (most recent call last):
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/retry.py", line 161, in retry_sync
    raise e
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/retry.py", line 144, in retry_sync
    return process_response(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/process_response.py", line 153, in process_response
    model = response_model.from_response(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/function_calls.py", line 163, in from_response
    return cls.parse_json(completion, validation_context, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/function_calls.py", line 360, in parse_json
    return cls.model_validate_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/pydantic/main.py", line 625, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Result
paragraph_indexes
  Field required [type=missing, input_value={'Title': 'Result', 'Paragraph Indexes': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/retry.py", line 134, in retry_sync
    for attempt in max_retries:
                   ^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x14a8b1fa0 state=finished raised ValidationError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bastil/bin/yt2doc/.venv/bin/yt2doc", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/typer/main.py", line 338, in __call__
    raise e
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/typer/main.py", line 321, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/typer/core.py", line 665, in main
    return _main(
           ^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/typer/core.py", line 197, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/typer/main.py", line 703, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/cli.py", line 146, in main
    formatted_transcript = yt2doc.video_to_document(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/yt2doc.py", line 26, in video_to_document
    formatted_transcript = self.formatter.format_chaptered_transcript(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/formatter.py", line 52, in format_chaptered_transcript
    chapters = self.topic_segmenter.segment(paragraphs=paragraphed_sentences)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/yt2doc/formatting/llm_topic_segmenter.py", line 90, in segment
    result = self.llm_client.chat.completions.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/client.py", line 172, in create
    return self.create_fn(
           ^^^^^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/patch.py", line 188, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/bastil/bin/yt2doc/.venv/lib/python3.12/site-packages/instructor/retry.py", line 164, in retry_sync
    raise InstructorRetryException(
instructor.exceptions.InstructorRetryException: 1 validation error for Result
paragraph_indexes
  Field required [type=missing, input_value={'Title': 'Result', 'Paragraph Indexes': []}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

Command used:
`yt2doc --video https://www.youtube.com/watch\?v\=-J88th7vZ34 --output ~/Documents/03\ -\ Resources/web-capture/ --segment-unchaptered --llm-model mistral:latest`

**Comment by shun-liang** [comment]
Also, have you tried it with gemma2 9b? So far, for my personal experience gemma2 9b seems to work the best for formatting.

**Comment by BastLeblanc** [comment]
> Also, have you tried it with gemma2 9b? So far, for my personal experience gemma2 9b seems to work the best for formatting.

will try and report back

**Comment by BastLeblanc** [comment]
That works with `gemma2:9b`, so closing this. Thanks for your help
